# Generated by Django 5.0.1 on 2024-07-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adjective',
            fields=[
                ('paradigm', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('forms', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('paradigm', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('ending', models.CharField(max_length=20)),
                ('orist_aoristos', models.CharField(max_length=20)),
                ('ypot_aoristos', models.CharField(max_length=20)),
                ('metochi', models.CharField(max_length=20)),
                ('ypot_enestotas', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Noun',
            fields=[
                ('paradigm', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('gen_sing', models.CharField(max_length=20)),
                ('plural', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.source')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('nowakowski', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kostakis', models.CharField(max_length=50, null=True)),
                ('greek', models.CharField(max_length=200, null=True)),
                ('paradigm', models.CharField(max_length=5, null=True)),
                ('lemma', models.CharField(max_length=50, null=True)),
                ('ipa', models.CharField(max_length=50, null=True)),
                ('leonidio', models.BooleanField(default=False, null=True)),
                ('voskina', models.BooleanField(default=False, null=True)),
                ('pragmateutis', models.BooleanField(default=False, null=True)),
                ('sampatiki', models.BooleanField(default=False, null=True)),
                ('livadi', models.BooleanField(default=False, null=True)),
                ('tyros', models.BooleanField(default=False, null=True)),
                ('melana', models.BooleanField(default=False, null=True)),
                ('sapounakaiika', models.BooleanField(default=False, null=True)),
                ('palaiochora', models.BooleanField(default=False, null=True)),
                ('agios_andreas', models.BooleanField(default=False, null=True)),
                ('kastanitsa', models.BooleanField(default=False, null=True)),
                ('sitaina', models.BooleanField(default=False, null=True)),
                ('prastos', models.BooleanField(default=False, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.source')),
            ],
        ),
    ]
