# Generated by Django 4.2.4 on 2023-09-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsakonian', models.CharField(max_length=50)),
                ('greek', models.CharField(max_length=200)),
                ('paradigm', models.CharField(max_length=5)),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.source')),
            ],
        ),
    ]
