# Generated by Django 4.2.4 on 2023-10-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('paradigm_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='paradigm',
        ),
        migrations.AddField(
            model_name='entry',
            name='paradigm_id',
            field=models.ForeignKey(default='Χ', on_delete=django.db.models.deletion.CASCADE, to='dictionary.paradigm'),
        ),
    ]
